export const CREATE_COMMANDE_REQUEST = 'CREATE_COMMANDE_REQUEST'
export const CREATE_COMMANDE_SUCCESS = 'CREATE_COMMANDE_SUCCESS'
export const CREATE_COMMANDE_FAIL = 'CREATE_COMMANDE_FAIL'

export const MY_COMMANDES_REQUEST = 'MY_COMMANDES_REQUEST'
export const MY_COMMANDES_SUCCESS = 'MY_COMMANDES_SUCCESS'
export const MY_COMMANDES_FAIL = 'MY_COMMANDES_FAIL'

export const ALL_COMMANDES_REQUEST = 'ALL_COMMANDES_REQUEST'
export const ALL_COMMANDES_SUCCESS = 'ALL_COMMANDES_SUCCESS'
export const ALL_COMMANDES_FAIL = 'ALL_COMMANDES_FAIL'

export const UPDATE_COMMANDE_REQUEST = 'UPDATE_COMMANDE_REQUEST'
export const UPDATE_COMMANDE_SUCCESS = 'UPDATE_COMMANDE_SUCCESS'
export const UPDATE_COMMANDE_RESET = 'UPDATE_COMMANDE_RESET'
export const UPDATE_COMMANDE_FAIL = 'UPDATE_COMMANDE_FAIL'

export const DELETE_COMMANDE_REQUEST = 'DELETE_COMMANDE_REQUEST'
export const DELETE_COMMANDE_SUCCESS = 'DELETE_COMMANDE_SUCCESS'
export const DELETE_COMMANDE_RESET = 'DELETE_COMMANDE_RESET'
export const DELETE_COMMANDE_FAIL = 'DELETE_COMMANDE_FAIL'

export const COMMANDE_DETAILS_REQUEST = 'COMMANDE_DETAILS_REQUEST'
export const COMMANDE_DETAILS_SUCCESS = 'COMMANDE_DETAILS_SUCCESS'
export const COMMANDE_DETAILS_FAIL = 'COMMANDE_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'