export const ADMIN_PRODUITS_REQUEST = 'ADMIN_PRODUITS_REQUEST'
export const ADMIN_PRODUITS_SUCCESS = 'ADMIN_PRODUITS_SUCCESS'
export const ADMIN_PRODUITS_FAIL = 'ADMIN_PRODUITS_FAIL'

export const ALL_PRODUITS_REQUEST = 'ALL_PRODUITS_REQUEST'
export const ALL_PRODUITS_SUCCESS = 'ALL_PRODUITS_SUCCESS'
export const ALL_PRODUITS_FAIL = 'ALL_PRODUITS_FAIL'

export const NEW_PRODUIT_REQUEST = 'NEW_PRODUIT_REQUEST'
export const NEW_PRODUIT_SUCCESS = 'NEW_PRODUIT_SUCCESS'
export const NEW_PRODUIT_RESET = 'NEW_PRODUIT_RESET'
export const NEW_PRODUIT_FAIL = 'NEW_PRODUIT_FAIL'

export const DELETE_PRODUIT_REQUEST = 'DELETE_PRODUIT_REQUEST'
export const DELETE_PRODUIT_SUCCESS = 'DELETE_PRODUIT_SUCCESS'
export const DELETE_PRODUIT_RESET = 'DELETE_PRODUIT_RESET'
export const DELETE_PRODUIT_FAIL = 'DELETE_PRODUIT_FAIL'

export const UPDATE_PRODUIT_REQUEST = 'UPDATE_PRODUIT_REQUEST'
export const UPDATE_PRODUIT_SUCCESS = 'UPDATE_PRODUIT_SUCCESS'
export const UPDATE_PRODUIT_RESET = 'UPDATE_PRODUIT_RESET'
export const UPDATE_PRODUIT_FAIL = 'UPDATE_PRODUIT_FAIL'

export const PRODUIT_DETAILS_REQUEST = 'PRODUIT_DETAILS_REQUEST'
export const PRODUIT_DETAILS_SUCCESS = 'PRODUIT_DETAILS_SUCCESS'
export const PRODUIT_DETAILS_FAIL = 'PRODUIT_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'